site_name: Levee

pages:

- Home: 'index.md'

- Sections:
    - Subcommands: 'subcommands.md'
    - HTTP: 'http.md'
    - Signals: 'signals.md'

include_next_prev: false

theme_dir: 'theme'
docs_dir: 'content'
