# cmake
name: cmake

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Ragel Setup
        run:  |
         sudo apt-get update && sudo apt-get install ragel -yq
         # && sudo apt-get install -yq libboost1.65-dev
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: '3.16.x'
      - name: CMake Build
        run: |
            mkdir -p build
            cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release
            cd build
            make
            make install 
